### ISSUE TITLE
Support for hashable pd.Series

### ISSUE THREAD

**Issue by BlinkyBillToo** [bra-fsn/hashable_df#1]
hashable_df does not support hashing a pd.Series as hashable_df uses .applymap, which is not supported by pd.Series.  Any chance you could add something like to following code to address?

    def hashable_s(series):
        """Return a Series with hashable cell values."""
        return series.apply(f)

Thank you, this simple code saved me a few headaches :-)

**Comment by bra-fsn** [comment]
https://github.com/bra-fsn/hashable_df/tree/0.0.6
